Esboço do framework de testes
A função TEST é chamada a cada teste finalizado e incrementa as
variáveis globais que armazenam os números de testes, falhas e
testes ignorados. A função RESULT_UNITY exibe o resultado final
dos testes quando o script encerra

diff --git a/shellUnity b/shellUnity
--- a/shellUnity
+++ b/shellUnity
@@ -14,6 +14,41 @@
 # 
 # Licença: .
 
+trap RESULT_UNITY exit
+
+NUMBER_OF_TESTS_UNITY="0"
+NUMBER_OF_FAILURES_UNITY="0"
+NUMBER_OF_IGNORED_UNITY="0"
+FINISHED_ALL_TESTS_UNITY="0"
+
+RESULT_UNITY(){
+	
+	FINISHED_ALL_TESTS_UNITY="1"
+	echo -e "\n-----------------------"
+	echo "$NUMBER_OF_TESTS_UNITY Tests $NUMBER_OF_FAILURES_UNITY Failures $NUMBER_OF_IGNORED_UNITY Ignored"
+	[ "$NUMBER_OF_FAILURES_UNITY" -eq "0" ] && TEST 0 && exit 0
+	TEST 1 && exit 1
+}
+
+TEST(){
+
+	NUMBER_OF_TESTS_UNITY=$((NUMBER_OF_TESTS_UNITY+1))
+
+	if [ "$FINISHED_ALL_TESTS_UNITY" == "0" ]
+	then
+		echo -n "$0:num:teste:"
+	fi
+
+	if [ "$1" == "0" ] 
+	then
+		echo -e "\033[42mPASS\033[m"
+	else
+		NUMBER_OF_FAILURES_UNITY=$((NUMBER_OF_FAILURES_UNITY+1))
+		echo -e "\033[41mFAIL\033[m"
+	fi
+	
+}
+
 TEST_FAIL(){
 	return 1
 }
@@ -43,8 +78,8 @@ TEST_MESSAGE(){
 TEST_ASSERT_EQUAL(){
 
 	CONDITION=$(echo "$1==$2" | bc -l)
-       	[ "$CONDITION" == "1" ] && return 0
-	return 1
+       	[ "$CONDITION" == "1" ] && TEST 0 && return 0
+	TEST 1 && return 1
 }
 
 TEST_ASSERT_NOT_EQUAL(){
